// Category data
export const categoryCompanies = {
  "Bulge Bracket Investment Banks (BBs)" : [
      "JP Morgan",
      "Goldman Sachs",
      "Morgan Stanley",
      "Bank of America",
      "Citi",
      "Barclays",
      "UBS",
      "Deutsche Bank",
    ],
    "In-Between-a-Banks (IBABs)" :[
      "Wells Fargo",
      "RBC",
      "HSBC",
      "BNP Paribas",
      "Mizuho",
      "Nomura",
      "BMO",
      "CITIC",
    ], "Elite Boutique Investment Banks (EBs)":  [
      "Centerview",
      "Evercore",
      "Guggenheim",
      "Lazard",
      "Moelis",
      "Perella Weinberg",
      "PJT Partners",
      "Qatalyst",
      "Rothschild",
    ],
    "Up-and-Coming Elite Boutique Investment Banks (UCEBs)":  [
      "LionTree Advisors",
      "Zaoui & Co.",
      "Robey Warshaw",
      "Lakeside Capital Advisers",
      "Dyal Co.",
    ],
   "Middle Market Banks (MMs)" : [
      "Baird",
      "Brown Gibbons Lang & Company",
      "Cowen",
      "Harris Williams",
      "Houlihan Lokey",
      "Janney",
      "Jefferies",
      "JMP",
      "Lincoln International",
      "Macquarie",
      "Needham",
      "Oppenheimer",
      "Piper Sandler",
      "PJ Solomon",
      "Raymond James",
      "Stephens",
      "Stifel",
      "Truist",
      "Wedbush",
      "William Blair",
    ],
   "Industry-Specific Boutiques (ISBs)": [
      "Leerink",
      "Ziegler",
      "FT Partners",
      "Raine Group",
      "Allen & Co.",
      "Seabury",
      "Telsey Advisory Group",
    ],
   "Other Banks (Merchant Banks, Hybrid Firms, and KPOs)": [
      "BDT Capital Partners",
      "Tudor Pickering Holt & Co.",
      "Raine Group",
      "Three Ocean Partners",
      "Lepe Partners",
    ],
  };
